apiVersion: v1
data:
  JAVA_OPTS: "-Dlogging.level.ntt.raios.nfmf.account={{ default .Values.global.loggingLevel .Values.accountmanagement.loggingLevel }} 
  -DACCOUNT_APP_URL={{ default .Values.global.url .Values.accountmanagement.billingAccount.url }}
  -DMONGO_URL={{ default .Values.global.mongo.url .Values.accountmanagement.mongo.url }}
  -DMONGO_DB={{ default .Values.global.mongo.db .Values.accountmanagement.mongo.db }}
  -DMONGO_USER={{ default .Values.global.mongo.user .Values.accountmanagement.mongo.user }}
  -DMONGO_PASSWD={{ default .Values.global.mongo.password .Values.accountmanagement.mongo.password }}"
kind: ConfigMap
metadata:
  labels:
    app: {{ template "tmfaccount.name" . }}
  name: ms-tmf-account-mgmt-configmap
  namespace: pbc