apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "tmfaccount.name" . }}
  labels: {{- include "tmfaccount.metaLabels" . | nindent 4 }}
  {{- with .Values.accountmanagement.deploymentAnnotations }}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
  labels: {{- include "tmfaccount.metaLabels" . | nindent 4 }}
spec:
  replicas: {{ default .Values.global.replicas .Values.accountmanagement.replicas }}
  selector:
    matchLabels: {{- include "pbcDeployment.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels: {{- include "tmfaccount.podLabels" . | nindent 8 }}
      {{- with .Values.accountmanagement.podAnnotations }}
      annotations: {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      containers:
        - name: ms-tmf-account-mgmt-configuration
          image: {{ default (print .Values.global.image.registry) .Values.accountmanagement.image.registry }}/{{ default "/tmf-account" .Values.accountmanagement.image.repository}}:{{ default .Values.global.image.tag .Values.accountmanagement.image.tag }}
          ports:
            - containerPort: {{ .Values.accountmanagement.port }}
              name: http-internal
          env:
            - name: JAVA_OPTS
              valueFrom:
                configMapKeyRef:
                  key: JAVA_OPTS
                  name: ms-tmf-account-mgmt-configmap