apiVersion: v1
kind: Service
metadata:
  labels: {{- include "tmfapplication.metaLabels" . | nindent 4 }}
  name: {{ template "tmfapplication.name" . }}-service
spec:
  selector: {{- include "tmfapplication.selectorLabels" . | nindent 4 }}
  ports:
    - name: applicationfunction-http
      port: {{ .Values.applicationfunction.port }}
      protocol: TCP
      targetPort: {{ .Values.applicationfunction.port }}
  type: {{ .Values.applicationfunction.typeService }}