apiVersion: v1
data:
  JAVA_OPTS: "-Dlogging.level.ntt.raios.nfmf.customermgmt={{ default .Values.global.loggingLevel .Values.customermanagement.loggingLevel }}   
  -DCUSTOMER_APP_URL={{ default .Values.global.url .Values.customermanagement.customer.url }}
  -DMONGO_URL={{ default .Values.global.mongo.url .Values.customermanagement.mongo.url }}
  -DMONGO_DB={{ default .Values.global.mongo.db .Values.customermanagement.mongo.db }}
  -DMONGO_USER={{ default .Values.global.mongo.user .Values.customermanagement.mongo.user }}
  -DMONGO_PASSWD={{ default .Values.global.mongo.password .Values.customermanagement.mongo.password }}"
kind: ConfigMap
metadata:
  labels:
    app: {{ template "tmfcustomer.name" . }}
  name: ms-tmf-customer-mgmt-configmap
  namespace: pbc