apiVersion: v1
kind: Service
metadata:
  labels: {{- include "tmfquality.metaLabels" . | nindent 4 }}
  name: {{ template "tmfquality.name" . }}-service
spec:
  selector: {{- include "tmfquality.selectorLabels" . | nindent 4 }}
  ports:
    - name: qualityondeman-http
      port: {{ .Values.qualityondeman.port }}
      protocol: TCP
      targetPort: {{ .Values.qualityondeman.port }}
  type: {{ .Values.qualityondeman.typeService }}