apiVersion: v1
kind: Service
metadata:
  labels: {{- include "tmfresourceinventory.metaLabels" . | nindent 4 }}
  name: {{ template "tmfresourceinventory.name" . }}-service
spec:
  selector: {{- include "tmfresourceinventory.selectorLabels" . | nindent 4 }}
  ports:
    - name: resourceinventorymanagement-http
      port: {{ .Values.resourceinventorymanagement.port }}
      protocol: TCP
      targetPort: {{ .Values.resourceinventorymanagement.port }}
  type: {{ .Values.resourceinventorymanagement.typeService }}